import Head from 'next/head'
import { Inter } from '@next/font/google'
import Card from '@/component/card/card'
import CardClientSide from '@/component/card-client-side/card-client-side'

const inter = Inter({ subsets: ['latin'] })

export default function Home({product}) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>SERVER SIDE</h1>
      <Card data={product}/>
      <h1>CLIENT SIDE</h1>
      <CardClientSide/>
    </>
  )
}

export async function getServerSideProps() {
const response = await fetch('https://kwm6eoos53.execute-api.us-east-1.amazonaws.com/prod/results')
 const data = await response.json();
 const product=  JSON.parse(data.body).contents[0].data;
  return {
    props: {
      product
    }
  }

}